services:

  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    ports:
      - 443:443
    image: mynginx:1.0
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - inception
    depends_on :
      - wordpress
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    image: mydb:1.0  
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    image: mywp:1.0
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - inception
    restart: always
    env_file:
      - .env

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress

networks:
  inception:
    driver: bridge
